# Site settings
title: XRG - XML and Web Engineering Research Group
email: klimek@xrg.cz
author: 
    name: "Jakub Klímek"
    twitter: jakub_klimek

description: > # this means to ignore newlines until "baseurl:"
  XRG - XML and Web Engineering Research Group
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xrg.cz" # the base hostname & protocol for your site

# Build settings
excerpt_separator: <!--more-->

gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap

langs:
  en:
    cs: česky
  cs:
    en: English